version: '3'

services:
  startup-mobile:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: startup-mobile
    restart: always
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - startup-network
    environment:
      CHOKIDAR_USEPOLLING: 'true' # enables hot-reloading on windows host.
      IS_DOCKER: 'true'

networks:
  startup-network:
    external: true
